platform :ios, '8.0'
target '详情界面'do
pod 'AFNetworking','~>3.0.0'
pod 'MJRefresh','~>3.1.10'
pod 'Masonry','~>1.0.1'
pod 'FlyImage','~>1.0'
pod 'FDFullscreenPopGesture','~>1.1'
pod 'MJExtension','~>3.0.11'
end
